const fs = require('fs');

const missingKeys = JSON.parse(fs.readFileSync('missing_keys.json', 'utf8'));

// We only need to overwrite those that were auto-generated or missing.
const enDict = {
  "Реферальна програма": "Referral Program",
  "Запроси подругу - отримай знижку 10%!": "Invite a friend - get a 10% discount!",
  "Ваша подруга отримає знижку 10% на перший запис, а ви 10% — на ваш наступний запис за кожну подругу!": "Your friend gets 10% off their first booking, and you get 10% off your next booking for each friend!",
  "Поділитися 💬": "Share 💬",
  "Копіювати 📄": "Copy 📄",
  "Запрошено": "Invited",
  "Ваша знижка": "Your Discount",
  "Мій Майстер": "My Master",
  "Поточний майстер": "Current Master",
  "💬 Написати": "💬 Message",
  "Відкріпитись": "Unlink",
  "Знайти або підключити майстра 🔍": "Find or connect a master 🔍",
  "Пошук за геолокацією або ввід коду": "Search by geolocation or enter code",
  "Вподобання": "Preferences",
  "Збережені дизайни (Обране)": "Saved Designs (Favorites)",
  "Переглянути збережені фото 💅": "View saved photos 💅",
  "Налаштування": "Settings",
  "Темна тема": "Dark Theme",
  "Push-сповіщення": "Push Notifications",
  "Telegram-бот": "Telegram Bot",
  "Вийти з акаунту": "Log Out",
  "Видалити мій акаунт назавжди": "Delete my account permanently",
  "Привіт! Записуйся до мене на манікюр через NailsBook Pro!": "Hi! Book a manicure with me via NailsBook Pro!",
  "клієнтам": "clients",
  "Видлення": "Deletion",
  "Ви впевнені, що хочете видалити цього клієнта з вашої бази?": "Are you sure you want to delete this client from your base?",
  "Немає візитів": "No visits",
  "Мої клієнти": "My Clients",
  "Запросити ще": "Invite more",
  "Пошук клієнтів...": "Search clients...",
  "Вибрати всіх": "Select all",
  "Розсилка": "Broadcast",
  "Нове повідомлення": "New message",
  "Буде надіслано:": "Will be sent to:",
  "Скасувати": "Cancel",
  "Відправити": "Send",
  "Дані клієнта": "Client Data",
  "Закрити": "Close",
  "Видалити": "Delete",
  "Зберегти": "Save",
  "САЛОН ": "SALON ",
  "МАЙСТЕР ": "MASTER ",
  "Створіть свій": "Create your",
  "Стиль": "Style",
  "Оберіть послугу та зручний час для вашого ідеального візиту.": "Choose a service and convenient time for your perfect visit.",
  "ПОСЛУГА": "SERVICE",
  "Вибір Дати": "Select Date",
  "Доступні години": "Available Hours",
  "Немає вільних віконець на цю дату.": "No available slots on this date.",
  "Правила візиту:": "Visit Rules:",
  "Будь ласка, приходьте вчасно. У разі запізнення або неможливості прийти — завчасно попередьте майстра у чаті.": "Please arrive on time. If you are late or unable to attend, please notify the master in the chat in advance.",
  "ЗАБРОНЮВАТИ ВІЗИТ": "BOOK VISIT",
  "ПН": "MON", "ВТ": "TUE", "СР": "WED", "ЧТ": "THU", "ПТ": "FRI", "СБ": "SAT", "НД": "SUN",
  "Салон": "Salon", "Майстер": "Master", "Дашборд": "Dashboard", "QR Код": "QR Code", "Статист.": "Stats", "Оплата": "Payment",
  "Мої Клієнти": "My Clients", "Налаштування Графіка": "Schedule Settings", "Робочий день": "Work Day",
  "Початок:": "Start:", "Кінець:": "End:", "Поч. Перерви:": "Break Start:", "Кін. Перерви:": "Break End:",
  "Час на клієнта (хв):": "Time per client (min):", "Скопіювати на всі дні": "Copy to all days",
  "Зберегти Розклад": "Save Schedule", "Записи на": "Appointments on",
  "📷 Фото (Опц.)": "📷 Photo (Opt.)", "Підтвердити": "Confirm",
  "Надіслати як Купон": "Send as Coupon", "Деталі за": "Details for",
  "Галерея": "Gallery", "Всі Роботи": "All Works", "Мої Портфоліо": "My Portfolios",
  "Повідомлення": "Messages",
  "Manage Subscription": "Manage Subscription", "Дані та Безпека": "Data & Security",
  "Privacy Policy": "Privacy Policy", "Terms of Use": "Terms of Use", "Support: t.me/nailbook_support": "Support: t.me/nailbook_support",
  "ОЧІКУЄ ПІДТВЕРДЖЕННЯ": "PENDING CONFIRMATION", "ОЧІКУЄ ПЕРЕДОПЛАТУ": "AWAITING PREPAYMENT",
  "ПІДТВЕРДЖЕНО": "CONFIRMED", "СКАСОВАНО": "CANCELLED", "ВИКОНАНО": "COMPLETED",
  "Мої Записи": "My Appointments", "Ви ще не маєте записів": "You have no appointments yet",
  "Майстер:": "Master:", "Ваш Майстер": "Your Master", "До сплати:": "To pay:", "грн": "UAH",
  "Реквізити на Оплату": "Payment Details", "Скасувати запис": "Cancel appointment", "Видалити з історії 🗑️": "Delete from history 🗑️",
  "Необхідна Передоплата": "Prepayment Required", "Реквізити на оплату": "Payment details", "Увага!": "Attention!",
  "Сплатіть передоплату та надішліть скріншот майстру в чат.": "Please pay the prepayment and send a screenshot to the master in the chat.",
  "Запис скасується автоматично до:": "Appointment will be automatically cancelled by:", "Відкрити посилання на оплату": "Open payment link",
  "Картка:": "Card:", "Банк:": "Bank:", "Не вказано": "Not specified", "Скопіювати номер картки": "Copy card number", "Сума:": "Amount:",
  "Аватар": "Avatar", "Логотип": "Logo", "Телефон": "Phone", "Назва салону (опц.)": "Salon name (opt.)",
  "Соціальні мережі (посилання або нікнейми)": "Social networks (links or nicknames)",
  "Instagram (без @)": "Instagram (without @)", "TikTok (без @)": "TikTok (without @)", "Обліковий запис Facebook": "Facebook account",
  "Новий пароль (залиште порожнім, щоб не змінювати)": "New password (leave blank to not change)",
  "Зберегти зміни": "Save changes", "Підписка": "Subscription", "Поточний тариф:": "Current tariff:",
  "Активних клієнтів:": "Active clients:", "Тріал закінчується:": "Trial ends:", "Сплачено до:": "Paid until:",
  "⭐️ Оновити до Pro": "⭐️ Upgrade to Pro", "💳 Керувати підпискою": "💳 Manage subscription",
  "📍 Зафіксувати геолокацію салону": "📍 Fix salon geolocation", "Дозвольте новим клієнтам поблизу знаходити вас на карті.": "Allow new clients nearby to find you on the map.",
  "Поточна адреса:": "Current address:", "Сповіщення Telegram": "Telegram Notifications",
  "Отримуйте сповіщення про нові записи прямо в Telegram.": "Receive notifications about new appointments directly in Telegram.",
  "💬 Підключити Telegram": "💬 Connect Telegram", "Запросити клієнта": "Invite client",
  "Згенеруйте тимчасовий код для клієнта.": "Generate a temporary code for the client.", "🔑 Згенерувати код": "🔑 Generate code",
  "Ваш код:": "Your code:", "Передайте його клієнту. Дійсний 24 години.": "Give it to the client. Valid for 24 hours.",
  
  // Hand-added
  "⚠️ Запити на підтвердження": "⚠️ Pending Requests",
  "Немає записів на цей день": "No records today",
  "Мої ціни (Прайс-лист)": "My Prices (Price list)",
  "+ Додати послугу": "+ Add service",
  "Додано в обране ❤️": "Added to favorites ❤️",
  "Обране ❤️": "Favorites ❤️"
};

const deDict = {
  // Most already done, just fill missing
  "Реферальна програма": "Empfehlungsprogramm",
  "Запроси подругу - отримай знижку 10%!": "Laden Sie einen Freund ein - erhalten Sie 10% Rabatt!",
  "Ваша подруга отримає знижку 10% на перший запис, а ви 10% — на ваш наступний запис за кожну подругу!": "Ihre Freundin erhält 10% Rabatt auf ihre erste Buchung und Sie erhalten 10% Rabatt auf Ihre nächste Buchung für jede Freundin!",
  "Поділитися 💬": "Teilen 💬",
  "Копіювати 📄": "Kopieren 📄",
  "Запрошено": "Eingeladen",
  "Ваша знижка": "Ihr Rabatt",
  "Мій Майстер": "Mein Meister",
  "Поточний майстер": "Aktueller Meister",
  "💬 Написати": "💬 Schreiben",
  "Відкріпитись": "Loslösen",
  "Знайти або підключити майстра 🔍": "Meister finden oder verbinden 🔍",
  "Пошук за геолокацією або ввід коду": "Suche nach Geolocation oder Code eingeben",
  "Вподобання": "Präferenzen",
  "Збережені дизайни (Обране)": "Gespeicherte Designs (Favoriten)",
  "Переглянути збережені фото 💅": "Gespeicherte Fotos ansehen 💅",
  "Налаштування": "Einstellungen",
  "Темна тема": "Dunkles Thema",
  "Push-сповіщення": "Push-Benachrichtigungen",
  "Telegram-бот": "Telegram Bot",
  "Вийти з акаунту": "Abmelden",
  "Видалити мій акаунт назавжди": "Mein Konto dauerhaft löschen",
  "Привіт! Записуйся до мене на манікюр через NailsBook Pro!": "Hallo! Buche eine Maniküre bei mir über NailsBook Pro!",
  "клієнтам": "Kunden",
  "Видлення": "Löschung",
  "Ви впевнені, що хочете видалити цього клієнта з вашої бази?": "Möchten Sie diesen Kunden wirklich aus Ihrer Basis löschen?",
  "Немає візитів": "Keine Besuche",
  "Мої клієнти": "Meine Kunden",
  "Запросити ще": "Mehr einladen",
  "Пошук клієнтів...": "Kunden suchen...",
  "Вибрати всіх": "Alle auswählen",
  "Розсилка": "Rundschreiben",
  "Нове повідомлення": "Neue Nachricht",
  "Буде надіслано:": "Wird gesendet an:",
  "Скасувати": "Abbrechen",
  "Відправити": "Senden",
  "Дані клієнта": "Kundendaten",
  "Закрити": "Schließen",
  "Видалити": "Löschen",
  "Зберегти": "Speichern",
  "САЛОН ": "SALON ",
  "МАЙСТЕР ": "MEISTER ",
  "Створіть свій": "Erstellen Sie Ihren",
  "Стиль": "Stil",
  "Оберіть послугу та зручний час для вашого ідеального візиту.": "Wählen Sie eine Dienstleistung und eine günstige Zeit.",
  "ПОСЛУГА": "SERVICE",
  "Вибір Дати": "Datum auswählen",
  "Доступні години": "Verfügbare Zeiten",
  "Немає вільних віконець на цю дату.": "Keine freien Termine an diesem Datum.",
  "Правила візиту:": "Besuchsregeln:",
  "Будь ласка, приходьте вчасно. У разі запізнення або неможливості прийти — завчасно попередьте майстра у чаті.": "Bitte seien Sie pünktlich. Wenn Sie sich verspäten oder nicht kommen können, benachrichtigen Sie den Meister im Chat.",
  "ЗАБРОНЮВАТИ ВІЗИТ": "TERMIN BUCHEN",
  "ПН": "MO", "ВТ": "DI", "СР": "MI", "ЧТ": "DO", "ПТ": "FR", "СБ": "SA", "НД": "SO",
  "Салон": "Salon", "Майстер": "Meister", "Дашборд": "Dashboard", "QR Код": "QR-Code", "Статист.": "Stat.", "Оплата": "Zahlung",
  "Мої Клієнти": "Meine Kunden", "Налаштування Графіка": "Zeitplaneinstellungen", "Робочий день": "Arbeitstag",
  "Початок:": "Start:", "Кінець:": "Ende:", "Поч. Перерви:": "Pause start:", "Кін. Перерви:": "Pause ende:",
  "Час на клієнта (хв):": "Zeit pro Kunde (Min):", "Скопіювати на всі дні": "Auf alle Tage kopieren",
  "Зберегти Розклад": "Zeitplan speichern", "Записи на": "Termine am",
  "📷 Фото (Опц.)": "📷 Foto (Opt.)", "Підтвердити": "Bestätigen",
  "Надіслати як Купон": "Als Gutschein senden", "Деталі за": "Details für",
  "Галерея": "Galerie", "Всі Роботи": "Alle Arbeiten", "Мої Портфоліо": "Mein Portfolio",
  "Повідомлення": "Nachrichten",
  "Manage Subscription": "Abonnement verwalten", "Дані та Безпека": "Daten & Sicherheit",
  "Privacy Policy": "Datenschutz", "Terms of Use": "Nutzungsbedingungen", "Support: t.me/nailbook_support": "Support: t.me/nailbook_support",
  "ОЧІКУЄ ПІДТВЕРДЖЕННЯ": "WARTET AUF BESTÄTIGUNG", "ОЧІКУЄ ПЕРЕДОПЛАТУ": "WARTET AUF VORAUSZAHLUNG",
  "ПІДТВЕРДЖЕНО": "BESTÄTIGT", "СКАСОВАНО": "STORNIERT", "ВИКОНАНО": "ABGESCHLOSSEN",
  "Мої Записи": "Meine Termine", "Ви ще не маєте записів": "Sie haben noch keine Termine",
  "Майстер:": "Meister:", "Ваш Майстер": "Ihr Meister", "До сплати:": "Zu zahlen:", "грн": "UAH",
  "Реквізити на Оплату": "Zahlungsdetails", "Скасувати запис": "Termin stornieren", "Видалити з історії 🗑️": "Aus Verlauf löschen 🗑️",
  "Необхідна Передоплата": "Vorauszahlung erforderlich", "Реквізити на оплату": "Zahlungsdetails", "Увага!": "Achtung!",
  "Сплатіть передоплату та надішліть скріншот майстру в чат.": "Bitte zahlen Sie den Vorschuss und senden Sie einen Screenshot.",
  "Запис скасується автоматично до:": "Termin wird automatisch storniert bis:", "Відкрити посилання на оплату": "Zahlungslink öffnen",
  "Картка:": "Karte:", "Банк:": "Bank:", "Не вказано": "Nicht angegeben", "Скопіювати номер картки": "Kartennummer kopieren", "Сума:": "Betrag:",
  "Аватар": "Avatar", "Логотип": "Logo", "Телефон": "Telefon", "Назва салону (опц.)": "Salonname (opt.)",
  "Соціальні мережі (посилання або нікнейми)": "Soziale Netzwerke (Links oder Spitznamen)",
  "Instagram (без @)": "Instagram (ohne @)", "TikTok (без @)": "TikTok (ohne @)", "Обліковий запис Facebook": "Facebook-Konto",
  "Новий пароль (залиште порожнім, щоб не змінювати)": "Neues Passwort (leer lassen um nicht zu ändern)",
  "Зберегти зміни": "Änderungen speichern", "Підписка": "Abonnement", "Поточний тариф:": "Aktueller Tarif:",
  "Активних клієнтів:": "Aktive Kunden:", "Тріал закінчується:": "Test endet:", "Сплачено до:": "Bezahlt bis:",
  "⭐️ Оновити до Pro": "⭐️ Upgrade auf Pro", "💳 Керувати підпискою": "💳 Abo verwalten",
  "📍 Зафіксувати геолокацію салону": "📍 Salon-Standort festlegen", "Дозвольте новим клієнтам поблизу знаходити вас на карті.": "Lassen Sie neue Kunden Sie auf der Karte finden.",
  "Поточна адреса:": "Aktuelle Adresse:", "Сповіщення Telegram": "Telegram-Benachrichtigungen",
  "Отримуйте сповіщення про нові записи прямо в Telegram.": "Erhalten Sie Benachrichtigungen über neue Termine in Telegram.",
  "💬 Підключити Telegram": "💬 Telegram verbinden", "Запросити клієнта": "Kunden einladen",
  "Згенеруйте тимчасовий код для клієнта.": "Temporären Code für Kunden generieren.", "🔑 Згенерувати код": "🔑 Code generieren",
  "Ваш код:": "Ihr Code:", "Передайте його клієнту. Дійсний 24 години.": "Dem Kunden geben. 24 Stunden gültig."
};

const plDict = {
  "Реферальна програма": "Program poleceń",
  "Запроси подругу - отримай знижку 10%!": "Zaproś przyjaciela - otrzymaj 10% zniżki!",
  "Ваша подруга отримає знижку 10% на перший запис, а ви 10% — на ваш наступний запис за кожну подругу!": "Twój przyjaciel otrzyma 10% zniżki na pierwszą wizytę, a Ty 10% na następną wizytę za każdego przyjaciela!",
  "Поділитися 💬": "Udostępnij 💬",
  "Копіювати 📄": "Kopiuj 📄",
  "Запрошено": "Zaproszono",
  "Ваша знижка": "Twoja zniżka",
  "Мій Майстер": "Mój Mistrz",
  "Поточний майстер": "Obecny Mistrz",
  "💬 Написати": "💬 Napisz",
  "Відкріпитись": "Odłącz",
  "Знайти або підключити майстра 🔍": "Znajdź lub połącz mistrza 🔍",
  "Пошук за геолокацією або ввід коду": "Szukaj po lokalizacji lub wpisz kod",
  "Вподобання": "Preferencje",
  "Збережені дизайни (Обране)": "Zapisane projekty (Ulubione)",
  "Переглянути збережені фото 💅": "Zobacz zapisane zdjęcia 💅",
  "Налаштування": "Ustawienia",
  "Темна тема": "Ciemny motyw",
  "Push-сповіщення": "Powiadomienia Push",
  "Telegram-бот": "Bot Telegram",
  "Вийти з акаунту": "Wyloguj się",
  "Видалити мій акаунт назавжди": "Usuń moje konto na zawsze",
  "Привіт! Записуйся до мене на манікюр через NailsBook Pro!": "Cześć! Zapisz się do mnie na manicure przez NailsBook Pro!",
  "клієнтам": "klientom",
  "Видлення": "Usunięcie",
  "Ви впевнені, що хочете видалити цього клієнта з вашої бази?": "Czy na pewno chcesz usunąć tego klienta ze swojej bazy?",
  "Немає візитів": "Brak wizyt",
  "Мої клієнти": "Moi klienci",
  "Запросити ще": "Zaproś więcej",
  "Пошук клієнтів...": "Szukaj klientów...",
  "Вибрати всіх": "Wybierz wszystkich",
  "Розсилка": "Biuletyn",
  "Нове повідомлення": "Nowa wiadomość",
  "Буде надіслано:": "Zostanie wysłane do:",
  "Скасувати": "Anuluj",
  "Відправити": "Wyślij",
  "Дані клієнта": "Dane klienta",
  "Закрити": "Zamknij",
  "Видалити": "Usuń",
  "Зберегти": "Zapisz",
  "САЛОН ": "SALON ",
  "МАЙСТЕР ": "MISTRZ ",
  "Створіть свій": "Stwórz swój",
  "Стиль": "Styl",
  "Оберіть послугу та зручний час для вашого ідеального візиту.": "Wybierz usługę i dogodny czas.",
  "ПОСЛУГА": "USŁUGA",
  "Вибір Дати": "Wybierz datę",
  "Доступні години": "Dostępne godziny",
  "Немає вільних віконець на цю дату.": "Brak wolnych terminów w tym dniu.",
  "Правила візиту:": "Zasady wizyty:",
  "Будь ласка, приходьте вчасно. У разі запізнення або неможливості прийти — завчасно попередьте майстра у чаті.": "Proszę przyjdź punktualnie. Jeśli się spóźnisz lub nie możesz przyjść, powiadom mistrza w czacie.",
  "ЗАБРОНЮВАТИ ВІЗИТ": "ZAREZERWUJ WIZYTĘ",
  "ПН": "PN", "ВТ": "WT", "СР": "ŚR", "ЧТ": "CZ", "ПТ": "PT", "СБ": "SB", "НД": "ND",
  "Салон": "Salon", "Майстер": "Mistrz", "Дашборд": "Panel", "QR Код": "Kod QR", "Статист.": "Stat.", "Оплата": "Płatność",
  "Мої Клієнти": "Moi Klienci", "Налаштування Графіка": "Ustawienia harmonogramu", "Робочий день": "Dzień roboczy",
  "Початок:": "Początek:", "Кінець:": "Koniec:", "Поч. Перерви:": "Początek przerwy:", "Кін. Перерви:": "Koniec przerwy:",
  "Час на клієнта (хв):": "Czas na klienta (min):", "Скопіювати на всі дні": "Skopiuj na wszystkie dni",
  "Зберегти Розклад": "Zapisz Harmonogram", "Записи на": "Zapisy na",
  "📷 Фото (Опц.)": "📷 Zdjęcie (Opc.)", "Підтвердити": "Potwierdź",
  "Надіслати як Купон": "Wyślij jako kupon", "Деталі за": "Szczegóły dla",
  "Галерея": "Galeria", "Всі Роботи": "Wszystkie Prace", "Мої Портфоліо": "Moje Portfolio",
  "Повідомлення": "Wiadomości",
  "Manage Subscription": "Zarządzaj subskrypcją", "Дані та Безпека": "Dane i bezpieczeństwo",
  "Privacy Policy": "Polityka prywatności", "Terms of Use": "Warunki korzystania", "Support: t.me/nailbook_support": "Wsparcie: t.me/nailbook_support",
  "ОЧІКУЄ ПІДТВЕРДЖЕННЯ": "CZEKA NA POTWIERDZENIE", "ОЧІКУЄ ПЕРЕДОПЛАТУ": "CZEKA NA ZALICZKĘ",
  "ПІДТВЕРДЖЕНО": "POTWIERDZONE", "СКАСОВАНО": "ANULOWANE", "ВИКОНАНО": "ZAKOŃCZONE",
  "Мої Записи": "Moje Wizyty", "Ви ще не маєте записів": "Nie masz jeszcze wizyt",
  "Майстер:": "Mistrz:", "Ваш Майстер": "Twój Mistrz", "До сплати:": "Do zapłaty:", "грн": "UAH",
  "Реквізити на Оплату": "Dane do płatności", "Скасувати запис": "Anuluj wizytę", "Видалити з історії 🗑️": "Usuń z historii 🗑️",
  "Необхідна Передоплата": "Wymagana przedpłata", "Реквізити на оплату": "Dane do płatności", "Увага!": "Uwaga!",
  "Сплатіть передоплату та надішліть скріншот майстру в чат.": "Zapłać przedpłatę i wyślij zrzut ekranu do mistrza w czacie.",
  "Запис скасується автоматично до:": "Wizyta zostanie automatycznie anulowana do:", "Відкрити посилання на оплату": "Otwórz link do płatności",
  "Картка:": "Karta:", "Банк:": "Bank:", "Не вказано": "Nie określono", "Скопіювати номер картки": "Skopiuj numer karty", "Сума:": "Kwota:",
  "Аватар": "Awatar", "Логотип": "Logo", "Телефон": "Telefon", "Назва салону (опц.)": "Nazwa salonu (opcj.)",
  "Соціальні мережі (посилання або нікнейми)": "Sieci społecznościowe (linki lub pseudonimy)",
  "Instagram (без @)": "Instagram (bez @)", "TikTok (без @)": "TikTok (bez @)", "Обліковий запис Facebook": "Konto Facebook",
  "Новий пароль (залиште порожнім, щоб не змінювати)": "Nowe hasło (pozostaw puste aby nie zmieniać)",
  "Зберегти зміни": "Zapisz zmiany", "Підписка": "Subskrypcja", "Поточний тариф:": "Obecny plan:",
  "Активних клієнтів:": "Aktywni klienci:", "Тріал закінчується:": "Okres próbny kończy się:", "Сплачено до:": "Opłacone do:",
  "⭐️ Оновити до Pro": "⭐️ Ulepsz do Pro", "💳 Керувати підпискою": "💳 Zarządzaj subskrypcją",
  "📍 Зафіксувати геолокацію салону": "📍 Ustaw lokalizację salonu", "Дозвольте новим клієнтам поблизу знаходити вас на карті.": "Pozwól nowym klientom w pobliżu znaleźć Cię na mapie.",
  "Поточна адреса:": "Obecny adres:", "Сповіщення Telegram": "Powiadomienia Telegram",
  "Отримуйте сповіщення про нові записи прямо в Telegram.": "Otrzymuj powiadomienia o nowych wizytach w aplikacji Telegram.",
  "💬 Підключити Telegram": "💬 Połącz Telegram", "Запросити клієнта": "Zaproś klienta",
  "Згенеруйте тимчасовий код для клієнта.": "Wygeneruj tymczasowy kod dla klienta.", "🔑 Згенерувати код": "🔑 Generuj kod",
  "Ваш код:": "Twój kod:", "Передайте його клієнту. Дійсний 24 години.": "Przekaż go klientowi. Ważny 24 godziny."
};

function assignDeep(obj, keyPath, value) {
  const keys = keyPath.split('.');
  let current = obj;
  for (let i = 0; i < keys.length - 1; i++) {
    if (!current[keys[i]]) current[keys[i]] = {};
    current = current[keys[i]];
  }
  current[keys[keys.length - 1]] = value;
}

function processLocale(loc, dict) {
    const filePath = `src/locales/${loc}.json`;
    if (!fs.existsSync(filePath)) return;
    
    let data = JSON.parse(fs.readFileSync(filePath, 'utf8'));
    
    for (const [keyPath, defaultUkValue] of Object.entries(missingKeys)) {
        if (dict[defaultUkValue]) {
            assignDeep(data, keyPath, dict[defaultUkValue]);
        } else {
            // Keep existing logic if not in dict
        }
    }
    
    fs.writeFileSync(filePath, JSON.stringify(data, null, 2), 'utf8');
}

processLocale('en', enDict);
processLocale('de', deDict);
processLocale('pl', plDict);

console.log("All locales translated.");
